language: rust
sudo: false
cache: cargo
rust:
- stable
- nightly
- 1.13.0
matrix:
  include:
  - os: osx
  - os: osx
    env: TARGET=x86_64-apple-ios RUST_BACKTRACE=1 RUST_TEST_THREADS=1
env:
- RUST_BACKTRACE=1 RUST_TEST_THREADS=1
before_script:
- if [ ! -z "$TARGET" ]; then
    rustup target add i386-apple-ios;
    rustup target add x86_64-apple-ios;
    rustup target add armv7-apple-ios;
    rustup target add armv7s-apple-ios;
    rustup target add aarch64-apple-ios;
  fi
script:
- if [ ! -z "$TARGET" ]; then
      cargo build --target=$TARGET;
      curl -LO https://github.com/SSheldon/rust-test-ios/releases/download/0.1.1/rust-test-ios;
      chmod +x rust-test-ios;
      ./rust-test-ios;
    else
      cargo test;
    fi
- if [ -z "$TARGET" ]; then
      rustdoc --test README.md -L target/debug/deps -L target/debug;
    fi;
