language: rust
sudo: false
cache: cargo
rust:
- nightly
- 1.9.0
matrix:
  include:
  - os: osx
    rust: 1.9.0
    env:
    - OPENSSL_INCLUDE_DIR=/usr/local/opt/openssl/include
    - OPENSSL_LIB_DIR=/usr/local/opt/openssl/lib
env:
- RUST_BACKTRACE=1
script:
- cargo test
