[package]
name = "native-tls"
version = "0.1.5"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A wrapper over a platform's native TLS implementation"
repository = "https://github.com/sfackler/rust-native-tls"
documentation = "https://docs.rs/native-tls/0.1.4/native_tls"
readme = "README.md"

[target.'cfg(any(target_os = "macos", target_os = "ios"))'.dependencies]
security-framework = "0.2"
security-framework-sys = "0.2"
lazy_static = "1.0"
libc = "0.2"
tempfile = "3.0"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = "0.1.12"

[target.'cfg(not(any(target_os = "windows", target_os = "macos", target_os = "ios")))'.dependencies]
openssl = "0.10.1"
