[package]
name = "native-tls"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "0.1.4"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = { version = "0.0.2", default-features = false }

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "0.7.10"
