[package]
name = "native-tls"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]
license = "MIT/Apache-2.0"
description = "A wrapper over a platform's native TLS implementation"
repository = "https://github.com/sfackler/rust-native-tls"
documentation = "https://sfackler.github.io/rust-native-tls/doc/v0.1.0/native_tls"
readme = "README.md"

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "0.1.5"
security-framework-sys = "0.1.5"
tempdir = "0.3"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = "0.1"

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "0.8.2"
openssl-verify = "0.2"

[replace]
"schannel:0.1.0" = { git = "https://github.com/steffengy/schannel-rs" }
"security-framework:0.1.8" = { git = "https://github.com/sfackler/rust-security-framework" }
"security-framework-sys:0.1.8" = { git = "https://github.com/sfackler/rust-security-framework" }
