[package]
name = "native-tls"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "0.1"

[target.'cfg(not(target_os = "macos"))'.dependencies]
openssl = "0.7"
