[package]
name = "native-tls"
version = "0.1.0"
authors = ["Steven Fackler <sfackler@gmail.com>"]

[target.'cfg(target_os = "macos")'.dependencies]
security-framework = "0.1.5"

[target.'cfg(target_os = "windows")'.dependencies]
schannel = "0.1"

[target.'cfg(not(any(target_os = "windows", target_os = "macos")))'.dependencies]
openssl = "0.8"
openssl-verify = "0.2"
